baseURL = "https://viscarra.dev/"
languageCode = "en-us"
title = "Rafael's stdout"
theme = "hugo-nuevo"
pygmentsStyle = "dracula"
staticDir = ["static"]
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License, please give source if you wish to quote or reproduce."

[params]
  customStyle = "styles/custom.scss"
  github = "rviscarra"
  linkedin = "rafael-viscarra-dev"
  email = "hello@viscarra.dev"
  fontAwesome = true

[markup]
  [markup.tableOfContents]
    startLevel = 3

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.es]
    contentDir = "content/es"
    languageName = "Español"
    weight = 20

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "GitHub"
  weight = 20
  identifier = "github"
  url = "https://github.com/rviscarra"

[[menu.main]]
  name = "About"
  weight = 30
  identifier = "about"
  url = "/about"
